<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">	
<plist version="1.0">	
<dict>
    <key>PayloadContent</key>
    <array>
        <dict>
	    <key>PayloadDescription</key>
	    <string>Configures restrictions</string>
	    <key>PayloadDisplayName</key>
	    <string>Restrictions</string>
	    <key>PayloadIdentifier</key>
	    <string>com.apple.applicationaccess.3CF474DA-AFEC-4378-9EEB-3F7F0717B596</string>
	    <key>PayloadType</key>
	    <string>com.apple.applicationaccess</string>
	    <key>PayloadUUID</key>
	    <string>3CF474DA-AFEC-4378-9EEB-3F7F0717B596</string>
	    <key>PayloadVersion</key>
	    <integer>1</integer>
        #General
        <key>allowCamera</key>
        <true/> 
        <key>allowDeviceSleep</key>
        <true/>
        <key>allowVideoConferencing</key>
        <true/> 
        <key>allowScreenShot</key>
        <true/>
        <key>allowProximitySetupToNewDevice</key>
        <false/>
        <key>allowVoiceDialing</key>
        <false/>
        <key>forceClassroomUnpromptedAppAndDeviceLock</key>
        <false/>
        <key>forceClassroomUnpromptedScreenObservation</key>
        <false/>
        <key>forceClassroomAutomaticallyJoinClasses</key>
        <false/>
        <key>forceClassroomRequestPermissionToLeaveClasses</key>
        <false/>
        <key>forceAutomaticDateAndTime</key>
        <false/>
        #Lock Screen
        <key>allowLockScreenControlCenter</key>
        <true/>
        <key>allowLockScrenNotificationsView</key>
        <true/>
        <key>allowLockScreenTodayView</key>
        <true/>
        <key>allowPassbookWhileLocked</key>
        <true/>
        #USB & Pairing
        <key>allowHostPairing</key>
        <true/>
        <key>allowUSBRestrictedMode</key>
        <false/>
        #Apps
        <key>allowAppClips</key>
        <true/>
        <key>allowUIAppInstallation</key>
        <true/>
        <key>allowAutomaticAppDownloads</key>
        <true/>
        <key>allowChat</key>
        <true/>
        <key>allowAppInstallation</key>
        <true/>
        <key>allowAppRemoval</key>
        <true/>
        <key>allowSystemAppRemoval</key>
        <true/>
        <key>allowEnterpriseAppTrust</key>
        <true/>
        <key>allowListedAppBundleIDs</key>
        <false/>
        #Managed Open-In
        <key>allowOpenFromManagedToUnmanaged</key>
        <false/>
        <key>allowOpenFromUnmanagedToManaged</key>
        <true/>
        <key>allowManagedAppsCloudSync</key>
        <false/>
        <key>forceAirDropUnmanaged</key>
        <true/>
        #iCloud
        <key>allowCloudBackup</key>
        <true/>
        <key>allowCloudDocumentSync</key>
        <true/>
        <key>allowCloudKeychainSync</key>
        <false/>
        <key>allowCloudPhotoLibrary</key>
        <true/>
        <key>allowPhotoStream</key>
        <true/>
        <key>allowSharedStream</key>
        <true/>
        #Safari
        <key>allowSafari</key>
        <true/>
        <key>safariAcceptCookies</key>
        <true/>
        <key>safariAllowAutoFill</key>
        <true/>
        <key>safariAllowJavaScript</key>
        <true/>
        <key>safariAllowPopups</key>
        <false/>
        <key>safariForceFraudWarning</key>
        <true/>
        #AirPrint
        <key>allowAirPrint</key>
        <true/>
        <key>allowAirPrintCredentialsStorage</key>
        <true/>
        <key>allowAirPrintiBeaconDiscovery</key>
        <true/>
        <key>forceAirPrintTrustedTLSRequirement</key>
        <true/>
        #Notifications
        <key>allowNotificationsModification</key>
        <true/>
        #Files
        <key>allowFilesNetworkDriveAccess</key>
        <true/>
        <key>allowFilesUSBDriveAccess</key>
        <true/>
        #Apple Watch
        <key>allowPairedWatch</key>
        <true/>
        <key>forceWatchWristDetection</key>
        <false/>
        #Network and connectivity
        <key>allowVPNCreation</key>
        <false/>
        #Security and Privacy
        <key>allowEnablingRestrictions</key>
        <true/>
        <key>allowEraseContentAndSettings</key>
        <false/>
        <Key>allowFindMyDevice</key>
        <true/>
        <key>allowFindMyFriends</key>
        <false/>
        <key>allowUIConfiguationProfileInstallation</key>
        <false/>
        <key>allowPasscodeModification</key>
        <true/>
        <key>allowPasswordAutofill</key>
        <true/>
        <key>allowPasswordSharing</key>
        <false/>
        <key>allowApplePersonalizedAdvertising</key>
        <false/>
        <key>allowPasswordProximityRequests</key>
        <false/>
        <key>allowDiagnosticSubmission</key>
        <false/>
        <key>allowFingerprintModification</key>
        <true/>
        <key>allowFingerprintForUnlock</key>
        <true/>
        <key>allowUnpairedExternalBootToRecovery</key>
        <false/>
        <key>allowUntrustedTLSPrompt</key>
        <false/>
        <key>forceEncryptedBackup</key>
        <true/>
        <key>forceLimitAdTracking</key>
        <true/>
        <key>allowAccountModification</key>
        <true/>
        <key>forceAuthenticationBeforeAutoFill</key>
        <true/>
        <key>forceDelayedSoftwareUpdates</key>
        <false/>
        <key>allowAssistantWhileLocked</key>
        <false/>
    <key>PayloadOrganization</key>
	<string>CBC</string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>ECC85AF7-1326-43F4-A517-80115B57A6CC</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>